TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devadrian.db
DATA += devadrian.proto

#=======================================
include $(TOP)/configure/RULES
